language: clojure
services: xvfb
jdk:
  - openjdk8
env:
  - NODE_VERSION=12 CC=clang CXX=clang++

before_install:
  - nvm install $NODE_VERSION

install:
  - make deps

cache:
  directories:
    - node_modules

script:
  - make test-ci
